name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install & Build (on GitHub)
        run: |
          npm install
          npm run build

      - name: Copy Files to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/,package.json,package-lock.json,ecosystem.config.cjs,deployment/"
          target: "~/calorie-backend"

      - name: Execute Remote Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/calorie-backend
            # Install only production dependencies to save RAM
            npm install --production

            # Update Nginx
            sudo cp deployment/nginx/calorie-tracker-api /etc/nginx/sites-available/
            sudo ln -sf /etc/nginx/sites-available/calorie-tracker-api /etc/nginx/sites-enabled/
            sudo nginx -t && sudo systemctl reload nginx

            # Restart App
            pm2 restart ecosystem.config.cjs --update-env
